# Generated by Django 3.2.9 on 2021-12-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
    ]
