# Generated by Django 3.2.9 on 2021-12-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211204_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Customer'), (1, 'Delivery')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tp_no',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
