# Generated by Django 3.2.9 on 2021-12-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tablereservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablereservation',
            old_name='time_from',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='time_to',
        ),
    ]
