# Generated by Django 3.2.9 on 2021-12-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211215_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablereservation',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tablereservation',
            name='date',
        ),
    ]
