# Generated by Django 3.2.9 on 2021-12-15 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tablereservation_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='date_time',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 14, 36, 29, 177652)),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 14, 36, 29, 177652)),
        ),
    ]
