# Generated by Django 3.2.9 on 2021-12-16 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211215_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 11, 57, 25, 825360)),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 11, 57, 25, 825360)),
        ),
    ]
