# Generated by Django 3.2.9 on 2021-12-16 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211216_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 13, 34, 41, 599711)),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 13, 34, 41, 599711)),
        ),
    ]
