# Generated by Django 3.2.9 on 2021-12-17 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211217_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomization',
            name='customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customization'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 18, 48, 33, 239202)),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 18, 48, 33, 239202)),
        ),
    ]
